### ISSUE TITLE
python3: AttributeError: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by AniketDeshmane** [scaidermern/piCamBot#8]
Exception in thread Image watch:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Downloads/SecuritySys/piCamBot-master/piCamBot.py", line 398, in fetchImageUpdates
    notify.add_watch(watch_dir.encode('utf-8'))
  File "/home/pi/.local/lib/python3.5/site-packages/inotify/adapters.py", line 93, in add_watch
    path_bytes = path_unicode.encode('utf8')
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by scaidermern** [comment]
Should be fixed in the newest master version (hopefully, since I can't test it right now). Thanks for the bug report!
